# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='reputation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
