# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botCore', '0002_questions_reputation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
